'use client';

import React, { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { useAppStore } from '@/store/useAppStore';
import { BurnAnimation, CrumpleAnimation, DeleteAnimation, ShredAnimation, BlackholeAnimation } from '@/components/animations';
import { generateFeedback } from '@/services/aiService';
import { RefreshCcw, Home as HomeIcon, Download } from 'lucide-react';
import { motion } from 'framer-motion';
import html2canvas from 'html2canvas';

export default function FeedbackPage() {
  const router = useRouter();
  const { currentEmotion, destructionMethod, reset, addToHistory } = useAppStore();
  const [animationComplete, setAnimationComplete] = useState(false);
  const [aiFeedback, setAiFeedback] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const feedbackRequested = useRef(false);
  const cardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!currentEmotion || !destructionMethod) {
      router.push('/');
    }
  }, [currentEmotion, destructionMethod, router]);

  const handleAnimationComplete = () => {
    setAnimationComplete(true);
    if (!feedbackRequested.current) {
      feedbackRequested.current = true;
      setIsGenerating(true);
      
      // Save to history
      addToHistory({
        id: Date.now().toString(),
        content: currentEmotion,
        method: destructionMethod!,
        timestamp: Date.now(),
        quote: '' // Will be populated if we stored the feedback, but for now we stream it
      });

      generateFeedback(currentEmotion, (chunk) => {
        setAiFeedback(prev => prev + chunk);
      }).finally(() => {
        setIsGenerating(false);
      });
    }
  };

  const handleRestart = () => {
    reset();
    router.push('/');
  };

  const handleSaveImage = async () => {
    if (!cardRef.current) return;
    
    setIsSaving(true);
    try {
      const canvas = await html2canvas(cardRef.current, {
        scale: 2, // Higher quality
        backgroundColor: '#ffffff',
        useCORS: true
      });
      
      const image = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.href = image;
      link.download = `emotion-trash-card-${Date.now()}.png`;
      link.click();
    } catch (error) {
      console.error('Failed to save image:', error);
    } finally {
      setIsSaving(false);
    }
  };

  if (!currentEmotion || !destructionMethod) return null;

  return (
    <div className="flex flex-col items-center justify-center min-h-screen w-full max-w-4xl mx-auto px-4 py-12">
      {!animationComplete ? (
        <div className="w-full">
          {destructionMethod === 'burn' && (
            <BurnAnimation content={currentEmotion} onComplete={handleAnimationComplete} />
          )}
          {destructionMethod === 'crumple' && (
            <CrumpleAnimation content={currentEmotion} onComplete={handleAnimationComplete} />
          )}
          {destructionMethod === 'delete' && (
            <DeleteAnimation content={currentEmotion} onComplete={handleAnimationComplete} />
          )}
          {destructionMethod === 'shred' && (
            <ShredAnimation content={currentEmotion} onComplete={handleAnimationComplete} />
          )}
          {destructionMethod === 'blackhole' && (
            <BlackholeAnimation content={currentEmotion} onComplete={handleAnimationComplete} />
          )}
          <p className="text-center text-gray-500 mt-8 animate-pulse">
            正在销毁你的坏情绪...
          </p>
        </div>
      ) : (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="w-full max-w-2xl"
        >
          {/* Card to capture */}
          <div 
            ref={cardRef}
            className="bg-white p-8 rounded-3xl shadow-xl border border-gray-100 mb-8"
          >
            <div className="text-center mb-8">
              <h2 className="text-2xl font-bold text-blue-900 mb-2">情绪已清空</h2>
              <p className="text-gray-500">所有的烦恼都已随风而去</p>
            </div>

            <div className="bg-blue-50 p-6 rounded-xl mb-8 relative overflow-hidden">
              <div className="absolute top-0 left-0 w-1 h-full bg-orange-500" />
              <h3 className="text-sm font-bold text-orange-500 uppercase tracking-wider mb-2">
                来自AI的温暖寄语
              </h3>
              <p className="text-lg text-gray-800 leading-relaxed min-h-[100px] whitespace-pre-wrap">
                {aiFeedback}
                {isGenerating && <span className="inline-block w-2 h-4 ml-1 bg-orange-500 animate-pulse"/>}
              </p>
            </div>
            
            <div className="text-center text-xs text-gray-400 mt-4">
              Generated by 情绪垃圾桶
            </div>
          </div>

          <div className="flex flex-wrap justify-center gap-4">
            <button
              onClick={handleRestart}
              className="flex items-center gap-2 px-6 py-3 bg-gray-100 text-gray-700 rounded-full font-medium hover:bg-gray-200 transition-colors"
            >
              <RefreshCcw size={20} />
              <span>再次释放</span>
            </button>
            
            <button
              onClick={handleSaveImage}
              disabled={isSaving || isGenerating}
              className={`flex items-center gap-2 px-6 py-3 rounded-full font-medium transition-colors ${
                isSaving || isGenerating 
                  ? 'bg-blue-300 text-white cursor-wait' 
                  : 'bg-blue-600 text-white hover:bg-blue-700'
              }`}
            >
              <Download size={20} />
              <span>{isSaving ? '保存中...' : '保存卡片'}</span>
            </button>

            <button
              onClick={() => router.push('/')}
              className="flex items-center gap-2 px-6 py-3 bg-blue-900 text-white rounded-full font-medium hover:bg-blue-800 transition-colors"
            >
              <HomeIcon size={20} />
              <span>返回首页</span>
            </button>
          </div>
        </motion.div>
      )}
    </div>
  );
}
